# Generated by Django 4.1.1 on 2022-10-06 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yandexdirecttoken',
            name='scope',
        ),
    ]
