# Generated by Django 4.1.1 on 2022-11-07 16:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0004_mytargettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.IntegerField()),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'agency_clients',
                'ordering': ['user', 'source', 'name'],
                'default_related_name': 'agency_clients',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('yandex_direct', 'Яндекс Директ'), ('my_target', 'myTarget'), ('vk_ads', 'VK ADS')], max_length=256)),
            ],
            options={
                'db_table': 'sources',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VkAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('account_id', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vk_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vk_accounts',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('expires_in', models.IntegerField()),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.source')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tokens',
                'ordering': ['user', 'source'],
                'default_related_name': 'tokens',
            },
        ),
        migrations.CreateModel(
            name='StatisticByAgencyClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('date', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.agencyclient')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.source')),
            ],
            options={
                'db_table': 'statistic_by_agency_clients',
                'ordering': ['client', 'source', '-date'],
                'default_related_name': 'statistic_by_agency_clients',
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('campaign_id', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.agencyclient')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.source')),
            ],
            options={
                'db_table': 'campaigns',
                'ordering': ['client', 'source', 'name'],
                'default_related_name': 'campaigns',
            },
        ),
        migrations.CreateModel(
            name='BalanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.campaign')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.agencyclient')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.source')),
            ],
            options={
                'db_table': 'balance_history',
                'ordering': ['client', '-date', 'amount'],
                'default_related_name': 'balance_history',
            },
        ),
        migrations.AddField(
            model_name='agencyclient',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.vkaccount'),
        ),
        migrations.AddField(
            model_name='agencyclient',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.source'),
        ),
        migrations.AddField(
            model_name='agencyclient',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
