# Generated by Django 4.1.1 on 2022-11-07 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_agencyclient_source_vkaccount_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vkadstoken',
            name='user',
        ),
        migrations.RemoveField(
            model_name='yandexdirecttoken',
            name='user',
        ),
        migrations.DeleteModel(
            name='MyTargetToken',
        ),
        migrations.DeleteModel(
            name='VkAdsToken',
        ),
        migrations.DeleteModel(
            name='YandexDirectToken',
        ),
    ]
