# Generated by Django 4.1.1 on 2022-11-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_vkadstoken_user_remove_yandexdirecttoken_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(choices=[('yandex_direct', 'Яндекс Директ'), ('my_target', 'myTarget'), ('vk_ads', 'VK ADS')], max_length=256, unique=True),
        ),
    ]
